// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package com_cinema_srv_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             int64    `protobuf:"varint,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26820c49b42a8106, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26820c49b42a8106, []int{1}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             int64    `protobuf:"varint,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Nickname             string   `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26820c49b42a8106, []int{2}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginResponse) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *LoginResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

// 返回用户id
type ResponseUserId struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseUserId) Reset()         { *m = ResponseUserId{} }
func (m *ResponseUserId) String() string { return proto.CompactTextString(m) }
func (*ResponseUserId) ProtoMessage()    {}
func (*ResponseUserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26820c49b42a8106, []int{3}
}
func (m *ResponseUserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUserId.Unmarshal(m, b)
}
func (m *ResponseUserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUserId.Marshal(b, m, deterministic)
}
func (dst *ResponseUserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUserId.Merge(dst, src)
}
func (m *ResponseUserId) XXX_Size() int {
	return xxx_messageInfo_ResponseUserId.Size(m)
}
func (m *ResponseUserId) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUserId.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUserId proto.InternalMessageInfo

func (m *ResponseUserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	// 响应是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 响应信息
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26820c49b42a8106, []int{4}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "com.cinema.srv.user.User")
	proto.RegisterType((*LoginRequest)(nil), "com.cinema.srv.user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "com.cinema.srv.user.LoginResponse")
	proto.RegisterType((*ResponseUserId)(nil), "com.cinema.srv.user.ResponseUserId")
	proto.RegisterType((*Response)(nil), "com.cinema.srv.user.Response")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_user_26820c49b42a8106) }

var fileDescriptor_user_26820c49b42a8106 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x9d, 0xfe, 0xf7, 0xfa, 0xcb, 0x28, 0x12, 0x0b, 0x42, 0x9d, 0x55, 0x57, 0x11, 0x14,
	0x7c, 0x01, 0x41, 0x14, 0x5c, 0x45, 0xfb, 0x00, 0x69, 0x7a, 0x69, 0x83, 0x66, 0x26, 0xce, 0x4d,
	0x2b, 0xbe, 0x8e, 0x7b, 0x9f, 0xc2, 0x17, 0x93, 0x3b, 0xc9, 0x14, 0x03, 0xb1, 0x5b, 0x37, 0x21,
	0x67, 0xbe, 0x93, 0x93, 0x73, 0xb9, 0x03, 0x87, 0x2b, 0x42, 0x7b, 0xc9, 0x8f, 0x30, 0xb7, 0xa6,
	0x30, 0xf2, 0x38, 0x31, 0x59, 0x98, 0xa4, 0x1a, 0xb3, 0x38, 0x24, 0xbb, 0x0e, 0x19, 0xa9, 0x4f,
	0x01, 0x9d, 0x29, 0xa1, 0x95, 0x23, 0x18, 0xe8, 0x34, 0x79, 0xd1, 0x71, 0x86, 0x81, 0x18, 0x8b,
	0xc9, 0x30, 0xda, 0x68, 0x66, 0x6c, 0x76, 0xac, 0x55, 0x32, 0xaf, 0x99, 0xe5, 0x31, 0xd1, 0xbb,
	0xb1, 0xf3, 0xa0, 0x5d, 0x32, 0xaf, 0xe5, 0x09, 0x74, 0xf3, 0xa5, 0xd1, 0x18, 0x74, 0x1c, 0x28,
	0x05, 0x9f, 0x62, 0x16, 0xa7, 0xaf, 0x41, 0xb7, 0x3c, 0x75, 0x82, 0x73, 0x66, 0xa9, 0x2d, 0x96,
	0xf3, 0xf8, 0x23, 0xe8, 0x8d, 0xc5, 0xa4, 0x1d, 0x6d, 0xb4, 0xba, 0x83, 0xbd, 0x47, 0xb3, 0x48,
	0x75, 0x84, 0x6f, 0x2b, 0xa4, 0xa2, 0xd6, 0x47, 0x6c, 0xe9, 0xd3, 0xaa, 0xf7, 0x51, 0xdf, 0x02,
	0xf6, 0xab, 0x20, 0xca, 0x8d, 0x26, 0x94, 0xa7, 0xd0, 0xe3, 0x2f, 0x1f, 0xe6, 0x55, 0x4e, 0xa5,
	0xfe, 0x7b, 0xe2, 0xda, 0x36, 0xfa, 0xf5, 0x6d, 0xa8, 0x09, 0x1c, 0xf8, 0xfe, 0xd3, 0xb2, 0xed,
	0x1f, 0x53, 0xa8, 0x1b, 0x18, 0x6c, 0x26, 0x0d, 0xa0, 0x4f, 0xab, 0x24, 0x41, 0x22, 0x67, 0x1a,
	0x44, 0x5e, 0xca, 0x23, 0x68, 0x67, 0xb4, 0xa8, 0xc6, 0xe4, 0xd7, 0xab, 0x2f, 0x01, 0xbb, 0x1c,
	0xfd, 0x84, 0x76, 0x9d, 0x26, 0x28, 0xef, 0x01, 0x6e, 0x2d, 0xc6, 0x85, 0xfb, 0x9f, 0x3c, 0x0b,
	0x1b, 0x2e, 0x52, 0xc8, 0x68, 0x74, 0xde, 0x88, 0x7c, 0x07, 0xb5, 0x23, 0x9f, 0x61, 0xc8, 0x46,
	0xb7, 0x04, 0x79, 0xd1, 0xe8, 0xfe, 0xbd, 0xe9, 0x91, 0xda, 0x66, 0xf1, 0xa9, 0xb3, 0x9e, 0xbb,
	0xe0, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac, 0x35, 0x37, 0x11, 0xf3, 0x02, 0x00, 0x00,
}
