// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package com_cinema_srv_user

import (
	_ "."
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             string   `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

type LoginRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 登陆成功后返回一个token
type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "com.cinema.srv.user.User")
	proto.RegisterType((*LoginRequest)(nil), "com.cinema.srv.user.LoginRequest")
	proto.RegisterType((*Token)(nil), "com.cinema.srv.user.Token")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74) }

var fileDescriptor_ed89022014131a74 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0xeb, 0xf4, 0x87, 0x76, 0xa8, 0x40, 0x32, 0x2c, 0x4c, 0x24, 0xa4, 0x92, 0x55, 0x57,
	0x46, 0xa2, 0xac, 0x91, 0x10, 0xdb, 0xae, 0x02, 0x1c, 0xc0, 0x4d, 0x46, 0xd4, 0x2a, 0xb6, 0x83,
	0xed, 0x14, 0x71, 0x25, 0x0e, 0xc2, 0xb9, 0x90, 0x6d, 0x5a, 0x51, 0x29, 0xb0, 0x89, 0xe6, 0xbd,
	0x79, 0x33, 0xf9, 0x32, 0x81, 0xd3, 0xd6, 0xa1, 0xbd, 0x0e, 0x0f, 0xde, 0x58, 0xe3, 0x0d, 0x3d,
	0xab, 0x8c, 0xe2, 0x95, 0xd4, 0xa8, 0x04, 0x77, 0x76, 0xcb, 0x43, 0x2b, 0x9f, 0x56, 0x46, 0x29,
	0xa3, 0x53, 0xa4, 0xf8, 0x24, 0x30, 0x78, 0x76, 0x68, 0xe9, 0x09, 0x64, 0xb2, 0x66, 0x64, 0x46,
	0xe6, 0xfd, 0x32, 0x93, 0x35, 0xcd, 0x61, 0xac, 0x65, 0xb5, 0xd1, 0x42, 0x21, 0xcb, 0x66, 0x64,
	0x3e, 0x29, 0xf7, 0x9a, 0x52, 0x18, 0x44, 0xbf, 0x1f, 0xfd, 0x58, 0x87, 0x7c, 0x23, 0x9c, 0x7b,
	0x37, 0xb6, 0x66, 0x83, 0x94, 0xdf, 0x69, 0x7a, 0x0e, 0xc3, 0x66, 0x6d, 0x34, 0xb2, 0x61, 0x6c,
	0x24, 0x11, 0x5c, 0x54, 0x42, 0xbe, 0xb2, 0x51, 0x72, 0xa3, 0x08, 0x7b, 0x56, 0xd2, 0xfa, 0x75,
	0x2d, 0x3e, 0xd8, 0x51, 0xda, 0xb3, 0xd3, 0xc5, 0x1d, 0x4c, 0x97, 0xe6, 0x45, 0xea, 0x12, 0xdf,
	0x5a, 0x74, 0x7e, 0xcf, 0x41, 0xfe, 0xe0, 0xc8, 0x0e, 0x39, 0x8a, 0x4b, 0x18, 0x3e, 0x99, 0x0d,
	0xea, 0xf0, 0x6a, 0x1f, 0x8a, 0x9f, 0xc9, 0x24, 0x6e, 0xbe, 0x08, 0x1c, 0x87, 0x5b, 0x3c, 0xa2,
	0xdd, 0xca, 0x0a, 0xe9, 0x2d, 0xc0, 0x83, 0x45, 0xe1, 0x31, 0x1e, 0xe8, 0x82, 0x77, 0x5c, 0x93,
	0x87, 0x56, 0x3e, 0xe1, 0x25, 0xba, 0xc6, 0x68, 0x87, 0x45, 0x8f, 0x2e, 0x61, 0x12, 0xcc, 0x08,
	0x4a, 0xaf, 0x3a, 0x87, 0x7e, 0x7f, 0x44, 0x9e, 0x77, 0x46, 0x22, 0x67, 0xd1, 0xa3, 0x0b, 0x18,
	0xdf, 0xb7, 0x7e, 0x1d, 0x09, 0xfe, 0x49, 0x1e, 0x20, 0xac, 0x46, 0xf1, 0xdf, 0x2e, 0xbe, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x80, 0x22, 0x2c, 0xa2, 0x11, 0x02, 0x00, 0x00,
}
