// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user/user.proto

/*
Package com_cinema_srv_user is a generated protocol buffer package.

It is generated from these files:
	user/user.proto

It has these top-level messages:
	User
	LoginRequest
	Token
*/
package com_cinema_srv_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "."

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = common.Response{}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	// 创建一个用户
	CreateUser(ctx context.Context, in *User, opts ...client.CallOption) (*common.Response, error)
	// 通过id获取用户
	UserLogin(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*Token, error)
	// 用户认证
	AuthUser(ctx context.Context, in *Token, opts ...client.CallOption) (*common.Response, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "com.cinema.srv.user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) CreateUser(ctx context.Context, in *User, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "UserService.CreateUser", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UserLogin(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "UserService.UserLogin", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) AuthUser(ctx context.Context, in *Token, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "UserService.AuthUser", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// 创建一个用户
	CreateUser(context.Context, *User, *common.Response) error
	// 通过id获取用户
	UserLogin(context.Context, *LoginRequest, *Token) error
	// 用户认证
	AuthUser(context.Context, *Token, *common.Response) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		CreateUser(ctx context.Context, in *User, out *common.Response) error
		UserLogin(ctx context.Context, in *LoginRequest, out *Token) error
		AuthUser(ctx context.Context, in *Token, out *common.Response) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) CreateUser(ctx context.Context, in *User, out *common.Response) error {
	return h.UserServiceHandler.CreateUser(ctx, in, out)
}

func (h *userServiceHandler) UserLogin(ctx context.Context, in *LoginRequest, out *Token) error {
	return h.UserServiceHandler.UserLogin(ctx, in, out)
}

func (h *userServiceHandler) AuthUser(ctx context.Context, in *Token, out *common.Response) error {
	return h.UserServiceHandler.AuthUser(ctx, in, out)
}
